# Generated by Django 4.2.9 on 2024-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userLevel',
            field=models.CharField(default='User', max_length=10),
        ),
    ]
