# Generated by Django 4.2.9 on 2024-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_home_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressFirstLine', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('dateOfLastOccupancy', models.DateField()),
                ('homeNotes', models.CharField(max_length=500)),
            ],
        ),
    ]
